### ISSUE TITLE
top nav bar 100% width

### ISSUE THREAD

**Issue by johnmarriott** [BSteffaniak/MikeMcDannaldLab#2]
fill in the left/right of the top nav bar

<img width="1186" alt="untitled" src="https://cloud.githubusercontent.com/assets/2177654/22092025/598de322-ddc0-11e6-9cb8-c52c517a5455.png">

**Comment by BSteffaniak** [comment]
mike wanted it like it is now

**Comment by johnmarriott** [comment]
🤔
