### ISSUE TITLE
Consider changing tab padding

### ISSUE THREAD

**Issue by johnmarriott** [BSteffaniak/MikeMcDannaldLab#5]
This is subjective but the left padding on the first tab should either be a little wider, or removed entirely.  I can elaborate if needed.

<img width="151" alt="line" src="https://cloud.githubusercontent.com/assets/2177654/23068639/18607cac-f4ea-11e6-907e-37e86f2fe65d.png">

**Comment by BSteffaniak** [comment]
Removed padding
